function trackers = config_tracker()
% config trackers to be evaluated
trackers = {
            struct('name', 'SiamDT', 'path', '..\tracking_results\Trained_with_antiuav410\SiamDT\',...
            'datastructure','1') ...
            struct('name', 'KeepTrack', 'path', '..\tracking_results\Trained_with_antiuav410\keep_track\',...
            'datastructure','1') ...
            struct('name', 'ToMP50', 'path', '..\tracking_results\Trained_with_antiuav410\tomp50\',...
            'datastructure','1') ...
            struct('name', 'SiamBAN', 'path', '..\tracking_results\Trained_with_antiuav410\SiamBAN\',...
            'datastructure','1') ...
            struct('name', 'Stark-ST101', 'path', '..\tracking_results\Trained_with_antiuav410\Stark\',...
            'datastructure','1') ...
            struct('name', 'AiATrack', 'path', '..\tracking_results\Trained_with_antiuav410\aiatrack\baseline\',...
            'datastructure','1') ...
            struct('name', 'SwinTrack-Tiny', 'path', '..\tracking_results\Trained_with_antiuav410\SwinTrack-Tiny\test_metrics\anti-uav410-test\',...
            'datastructure','2') ...
            };
end